site: Foundational
url: ""
title: Foundational
description: Charles Farr's blog on the underpinnings of modern life.
twitter:
  username: charlessimsfarr
  card: summary
  creator: #yourusername
author:
  twitter: charlessimsfarr
  name: "Charles Farr"
  avatar:
  email: #youremail
  url: #yoururl
permalink: pretty

baseurl: ''

highlighter: none

# Google Analytics
google_analytics: G-YFDETE1Z94

exclude:
  - .jekyll-cache

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

markdown: kramdown
